import assert from "node:assert/strict";
import test from "node:test";
import {previewStorageKeys} from "../lib/preferences";
import {addWidget,defaultDashboardLayout,moveWidget,normalizeDashboardLayout,removeWidget,resetDashboardLayout,resizeWidget,widgetDefinitions} from "../lib/dashboard-layout";

test("dashboard defaults provide direct daily-life widgets",()=>{const layout=defaultDashboardLayout();for(const type of ["quickAdd","todaySchedule","todayTasks","quickNotes","financeOverview"])assert.ok(layout.widgets.some(item=>item.type===type));assert.equal(new Set(layout.widgets.map(item=>item.id)).size,layout.widgets.length)});
test("dashboard normalization clamps geometry and preserves unknown widgets",()=>{const layout=normalizeDashboardLayout({version:0,widgets:[{id:"known",type:"quickAdd",cols:99,rows:0,config:{actions:["task"]}},{id:"future",type:"futureWidget",payload:{keep:true}}],futureSetting:"keep"});assert.equal(layout.widgets[0].cols,12);assert.equal(layout.widgets[0].rows,2);assert.deepEqual(layout.widgets[0].config,{actions:["task"]});assert.deepEqual(layout.unrecognizedWidgets,[{id:"future",type:"futureWidget",payload:{keep:true}}]);assert.equal((layout as unknown as {futureSetting:string}).futureSetting,"keep")});
test("dashboard layout operations are immutable and bounded",()=>{const source=defaultDashboardLayout(),first=source.widgets[0],second=source.widgets[1],moved=moveWidget(source,first.id,1);assert.equal(source.widgets[0].id,first.id);assert.equal(moved.widgets[0].id,second.id);assert.equal(resizeWidget(source,first.id,-99).widgets[0].cols,3);const added=addWidget(source,"wellbeing");assert.equal(added.widgets.at(-1)?.type,"wellbeing");assert.equal(added.widgets.at(-1)?.cols,widgetDefinitions.wellbeing.cols);assert.equal(removeWidget(added,added.widgets.at(-1)!.id).widgets.length,source.widgets.length)});
test("dashboard layout participates in encrypted workspace collection",()=>{assert.ok(previewStorageKeys.includes("kirpinova-dashboard-layout-v1"))});

test("removed and reset widgets keep user content recoverable",()=>{const source=defaultDashboardLayout(),note=source.widgets.find(item=>item.type==="quickNotes")!,withText={...source,widgets:source.widgets.map(item=>item.id===note.id?{...item,config:{text:"keep me"}}:item),unrecognizedWidgets:[{type:"future",content:"keep"}]};const removed=removeWidget(withText,note.id);assert.equal(removed.removedWidgets?.at(-1)?.config?.text,"keep me");const restored=addWidget(removed,"quickNotes");assert.equal(restored.widgets.at(-1)?.config?.text,"keep me");const reset=resetDashboardLayout(withText);assert.equal(reset.widgets.find(item=>item.type==="quickNotes")?.config?.text,"keep me");assert.deepEqual(reset.unrecognizedWidgets,withText.unrecognizedWidgets)});
