"use client";
import { FormEvent,useEffect,useMemo,useState } from "react";
import { CalendarEvent,calendarRepository } from "@/lib/calendar";
import { Task,taskRepository } from "@/lib/tasks";
const key=(d:Date)=>[d.getFullYear(),String(d.getMonth()+1).padStart(2,"0"),String(d.getDate()).padStart(2,"0")].join("-");
const Plus=()=> <svg aria-hidden="true" viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="M12 5v14M5 12h14"/></svg>;
const Arrow=({back=false}:{back?:boolean})=> <svg aria-hidden="true" viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" strokeWidth="1.8"><path d={back?"m15 6-6 6 6 6":"m9 6 6 6-6 6"}/></svg>;
const blank=(date:string):Omit<CalendarEvent,"id">=>({title:"",date,startTime:"09:00",endTime:"09:30",kind:"schedule",category:"Personal",notes:""});
export function CalendarWorkspace({onStatus}:{onStatus:(message:string)=>void}){
 const now=new Date(),[cursor,setCursor]=useState(new Date(now.getFullYear(),now.getMonth(),1)),[selected,setSelected]=useState(key(now)),[events,setEvents]=useState<CalendarEvent[]>([]),[tasks,setTasks]=useState<Task[]>([]),[editor,setEditor]=useState(false),[editing,setEditing]=useState<string|null>(null),[draft,setDraft]=useState(blank(key(now)));
 useEffect(()=>{setEvents(calendarRepository.load());setTasks(taskRepository.load())},[]);
 const days=useMemo(()=>{const first=new Date(cursor.getFullYear(),cursor.getMonth(),1),start=new Date(first);start.setDate(1-first.getDay());return Array.from({length:42},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);return d})},[cursor]);
 const selectedEvents=events.filter(x=>x.date===selected).sort((a,b)=>a.startTime.localeCompare(b.startTime));
 const selectedTasks=tasks.filter(x=>x.dueDate===selected);
 const monthLabel=cursor.toLocaleDateString(undefined,{month:"long",year:"numeric"});
 const changeMonth=(delta:number)=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth()+delta,1));
 const open=(event?:CalendarEvent)=>{setEditing(event?.id||null);setDraft(event?{title:event.title,date:event.date,startTime:event.startTime,endTime:event.endTime,kind:event.kind,category:event.category,notes:event.notes}:blank(selected));setEditor(true)};
 const save=(e:FormEvent)=>{e.preventDefault();const title=draft.title.trim();if(!title){onStatus("Add an event title before saving.");return}const next=editing?events.map(x=>x.id===editing?{...x,...draft,title}:x):[...events,{...draft,title,id:crypto.randomUUID()}];setEvents(next);calendarRepository.save(next);setSelected(draft.date);setEditor(false);onStatus(editing?"Event updated.":"Event added.")};
 const remove=()=>{if(!editing)return;const next=events.filter(x=>x.id!==editing);setEvents(next);calendarRepository.save(next);setEditor(false);onStatus("Event deleted.")};
 return <section className="calendar-workspace">
  <div className="calendar-toolbar"><div><button className="icon-button" onClick={()=>changeMonth(-1)} aria-label="Previous month"><Arrow back/></button><button className="month-jump" onClick={()=>{setCursor(new Date(now.getFullYear(),now.getMonth(),1));setSelected(key(now))}}>Today</button><button className="icon-button" onClick={()=>changeMonth(1)} aria-label="Next month"><Arrow/></button></div><h2>{monthLabel}</h2><button className="primary-button compact" onClick={()=>open()}><Plus/> Add event</button></div>
  <div className={editor?"calendar-layout with-editor":"calendar-layout"}><div className="calendar-main"><div className="weekday-row">{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(x=><span key={x}>{x}</span>)}</div><div className="month-grid">{days.map(day=>{const date=key(day),outside=day.getMonth()!==cursor.getMonth(),isToday=date===key(now),active=date===selected,dayEvents=events.filter(x=>x.date===date),dayTasks=tasks.filter(x=>x.dueDate===date&&!x.done);return <button key={date} className={["calendar-day",outside&&"outside",isToday&&"today",active&&"selected"].filter(Boolean).join(" ")} onClick={()=>setSelected(date)}><time dateTime={date}>{day.getDate()}</time><span className="day-items">{dayEvents.slice(0,2).map(x=><i className={x.kind} key={x.id}>{x.startTime} {x.title}</i>)}{dayTasks.slice(0,1).map(x=><i className="task" key={x.id}>{x.title}</i>)}{dayEvents.length+dayTasks.length>3&&<small>+{dayEvents.length+dayTasks.length-3} more</small>}</span></button>})}</div></div>
  <aside className="day-agenda"><div className="day-agenda-head"><div><span>Selected day</span><h3>{new Date(selected+"T12:00:00").toLocaleDateString(undefined,{weekday:"long",month:"long",day:"numeric"})}</h3></div><button className="icon-button small" onClick={()=>open()} aria-label="Add event on selected day"><Plus/></button></div>{selectedEvents.length===0&&selectedTasks.length===0?<div className="agenda-empty"><p>Nothing planned yet.</p><button className="text-button" onClick={()=>open()}>Add an event</button></div>:<div className="day-agenda-list">{selectedEvents.map(item=><button key={item.id} onClick={()=>open(item)}><time>{item.startTime}</time><i className={item.kind}/><span><strong>{item.title}</strong><small>{item.category} · {item.endTime}</small></span></button>)}{selectedTasks.map(task=><div className="agenda-task" key={task.id}><span>Task</span><strong>{task.title}</strong><small>{task.category}</small></div>)}</div>}</aside>
  {editor&&<aside className="event-editor"><div className="editor-heading"><div><span>{editing?"Editing event":"New event"}</span><h2>{editing?"Update the plan":"Add to the calendar"}</h2></div><button className="editor-close" onClick={()=>setEditor(false)}>Close</button></div><form onSubmit={save}><label className="field"><span>Event title</span><input autoFocus value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} placeholder="What is happening?"/></label><label className="field"><span>Date</span><input type="date" value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/></label><div className="editor-grid"><label className="field"><span>Starts</span><input type="time" value={draft.startTime} onChange={e=>setDraft({...draft,startTime:e.target.value})}/></label><label className="field"><span>Ends</span><input type="time" value={draft.endTime} onChange={e=>setDraft({...draft,endTime:e.target.value})}/></label></div><div className="editor-grid"><label className="field"><span>Type</span><select value={draft.kind} onChange={e=>setDraft({...draft,kind:e.target.value as CalendarEvent["kind"]})}><option value="schedule">Schedule</option><option value="blockout">Blockout</option></select></label><label className="field"><span>Category</span><input value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}/></label></div><label className="field"><span>Notes</span><textarea rows={3} value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/></label><div className="editor-actions">{editing&&<button type="button" className="danger-button" onClick={remove}>Delete</button>}<span/><button type="button" className="secondary-button" onClick={()=>setEditor(false)}>Cancel</button><button className="primary-button" type="submit">{editing?"Save changes":"Add event"}</button></div></form></aside>}</div>
 </section>
}
