"use client";

import {FormEvent,useEffect,useMemo,useRef,useState} from "react";
import {expenseTrend,taskCompletionTrend,wellbeingTrend} from "@/lib/analytics";
import {CalendarEvent,calendarRepository} from "@/lib/calendar";
import {convertAmount,ExchangeRates,loadExchangeRates} from "@/lib/currency";
import {DashboardLayout,DashboardWidget,DashboardWidgetType,addWidget,dashboardLayoutRepository,defaultDashboardLayout,moveWidget,removeWidget,resetDashboardLayout,resizeWidget,widgetDefinitions} from "@/lib/dashboard-layout";
import {DocumentRecord,documentRepository} from "@/lib/documents";
import {FinanceTransaction,financeRepository,money} from "@/lib/finance";
import {JournalEntry,journalRepository} from "@/lib/journal";
import {PersonRecord,peopleRepository} from "@/lib/people";
import {preferencesRepository} from "@/lib/preferences";
import {Task,emptyTaskDraft,taskRepository} from "@/lib/tasks";

type Destination="Tasks"|"Calendar"|"Finance"|"Documents"|"Journal"|"People";
type Props={onNavigate:(destination:Destination)=>void;onStatus:(message:string)=>void;quickAddRequest?:number};
const today=()=>new Date().toISOString().slice(0,10);
const Arrow=()=> <svg aria-hidden="true" viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="M5 12h14M14 7l5 5-5 5"/></svg>;
const Grip=()=> <svg aria-hidden="true" viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" strokeWidth="1.8"><circle cx="8" cy="7" r="1"/><circle cx="16" cy="7" r="1"/><circle cx="8" cy="12" r="1"/><circle cx="16" cy="12" r="1"/><circle cx="8" cy="17" r="1"/><circle cx="16" cy="17" r="1"/></svg>;
const Plus=()=> <svg aria-hidden="true" viewBox="0 0 24 24" width="17" height="17" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="M12 5v14M5 12h14"/></svg>;
const Check=()=> <svg aria-hidden="true" viewBox="0 0 24 24" width="15" height="15" fill="none" stroke="currentColor" strokeWidth="2"><path d="m5 12 4 4L19 6"/></svg>;
const Trend=({values,tone="brand",max}: {values:number[];tone?:string;max?:number})=>{const ceiling=max||Math.max(...values,1),points=values.map((value,index)=>`${10+index*(180/Math.max(1,values.length-1))},${60-Math.min(ceiling,value)/ceiling*48}`).join(" ");return <svg className={`dashboard-spark ${tone}`} viewBox="0 0 200 70" role="img" aria-label={values.join(", ")}><polyline points={points}/></svg>};

function reorder(layout:DashboardLayout,source:string,target:string){const widgets=[...layout.widgets],from=widgets.findIndex(item=>item.id===source),to=widgets.findIndex(item=>item.id===target);if(from<0||to<0||from===to)return layout;const[item]=widgets.splice(from,1);widgets.splice(to,0,item);return{...layout,widgets}}

export function DashboardWorkspace({onNavigate,onStatus,quickAddRequest=0}:Props){
 const[tasks,setTasks]=useState<Task[]>([]),[events,setEvents]=useState<CalendarEvent[]>([]),[finance,setFinance]=useState<FinanceTransaction[]>([]),[documents,setDocuments]=useState<DocumentRecord[]>([]),[people,setPeople]=useState<PersonRecord[]>([]),[journal,setJournal]=useState<JournalEntry[]>([]),[rates,setRates]=useState<ExchangeRates|null>(null),[reportCurrency,setReportCurrency]=useState<"TRY"|"EUR"|"USD"|"GBP">("TRY"),[layout,setLayout]=useState<DashboardLayout>(()=>defaultDashboardLayout()),[editing,setEditing]=useState(false),[library,setLibrary]=useState(false),[quickTask,setQuickTask]=useState(false),[dragged,setDragged]=useState("");
 const libraryDialog=useRef<HTMLDialogElement>(null);
 const refresh=()=>{setTasks(taskRepository.load());setEvents(calendarRepository.load());setFinance(financeRepository.load());setDocuments(documentRepository.load());setPeople(peopleRepository.load());setJournal(journalRepository.load());setReportCurrency(preferencesRepository.load().reportCurrency)};
 useEffect(()=>{refresh();setLayout(dashboardLayoutRepository.load());const controller=new AbortController();loadExchangeRates(controller.signal).then(setRates).catch(()=>undefined);const changed=()=>refresh();window.addEventListener("kirpinova:data-changed",changed);return()=>{controller.abort();window.removeEventListener("kirpinova:data-changed",changed)}},[]);
 useEffect(()=>{if(quickAddRequest>0)setQuickTask(true)},[quickAddRequest]);
 useEffect(()=>{const dialog=libraryDialog.current;if(library&&dialog&&!dialog.open)dialog.showModal()},[library]);
 const persist=(next:DashboardLayout)=>{setLayout(next);dashboardLayoutRepository.save(next)};
 const date=today(),month=date.slice(0,7),dayEvents=events.filter(item=>item.date===date).sort((a,b)=>a.startTime.localeCompare(b.startTime)),openTasks=tasks.filter(item=>!item.done).sort((a,b)=>(a.dueDate||"9999").localeCompare(b.dueDate||"9999")),dueDocuments=documents.filter(item=>item.status==="active"&&item.dueDate).sort((a,b)=>a.dueDate.localeCompare(b.dueDate)),favoritePeople=people.filter(item=>item.favorite).slice(0,4);
 const monthFinance=finance.filter(item=>item.date.startsWith(month)),totalsReady=!monthFinance.some(item=>item.currency!==reportCurrency)||Boolean(rates),sum=(type:FinanceTransaction["type"],impact?:FinanceTransaction["balanceImpact"])=>monthFinance.filter(item=>item.type===type&&(!impact||item.balanceImpact===impact)).reduce((total,item)=>total+(item.currency===reportCurrency?item.amount:rates?convertAmount(item.amount,item.currency,reportCurrency,rates.rates):0),0),income=sum("income"),expenses=sum("expense"),savings=sum("saving","cash"),balance=income-expenses-savings,totalMoney=(value:number)=>totalsReady?money(value,reportCurrency):"—";
 const completion=useMemo(()=>taskCompletionTrend(tasks),[tasks]),expensePoints=useMemo(()=>expenseTrend(finance),[finance]),wellbeing=useMemo(()=>wellbeingTrend(journal),[journal]);
 const saveQuickTask=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget),title=String(form.get("title")||"").trim();if(!title){onStatus("Enter a task title.");return}const draft=emptyTaskDraft(),next:Task={...draft,id:crypto.randomUUID(),title,dueDate:String(form.get("dueDate")||""),category:String(form.get("category")||"Personal"),priority:(form.get("priority")==="high"||form.get("priority")==="low"?form.get("priority"):"medium") as Task["priority"],createdAt:new Date().toISOString()};const all=[next,...taskRepository.load()];taskRepository.save(all);setTasks(all);event.currentTarget.reset();setQuickTask(false);onStatus("Task added from the dashboard.")};
 const toggleTask=(task:Task)=>{const next=tasks.map(item=>item.id===task.id?{...item,done:!item.done}:item);taskRepository.save(next);setTasks(next);onStatus(task.done?"Task reopened.":"Task completed.")};
 const updateNote=(widget:DashboardWidget,text:string)=>persist({...layout,widgets:layout.widgets.map(item=>item.id===widget.id?{...item,config:{...item.config,text}}:item)});
 const renderWidget=(widget:DashboardWidget)=>{switch(widget.type){
  case"quickAdd":return <div className="quick-actions-grid"><button onClick={()=>setQuickTask(value=>!value)}><Plus/><span><strong>Add task</strong><small>Save without leaving</small></span></button><button onClick={()=>onNavigate("Finance")}><span className="quick-action-symbol finance">+</span><span><strong>Open Finance</strong><small>Income, expense or saving</small></span></button><button onClick={()=>onNavigate("Journal")}><span className="quick-action-symbol journal">J</span><span><strong>Open Journal</strong><small>Capture a reflection</small></span></button><button onClick={()=>onNavigate("Documents")}><span className="quick-action-symbol document">D</span><span><strong>Open Documents</strong><small>Record or attachment</small></span></button></div>;
  case"todaySchedule":return <div className="widget-list">{dayEvents.length?dayEvents.slice(0,5).map(item=><button key={item.id} onClick={()=>onNavigate("Calendar")}><time>{item.startTime}</time><span><strong>{item.title}</strong><small>{item.category}{item.endTime?` · until ${item.endTime}`:""}</small></span></button>):<div className="widget-empty"><p>No timed moments today.</p><button className="text-button" onClick={()=>onNavigate("Calendar")}>Plan your day</button></div>}</div>;
  case"todayTasks":return <div className="widget-task-list">{openTasks.slice(0,5).map(task=><label key={task.id}><input type="checkbox" checked={task.done} onChange={()=>toggleTask(task)}/><span className="task-check"><Check/></span><span><strong>{task.title}</strong><small>{task.dueDate||"No due date"}{task.subtasks.length?` · ${task.subtasks.filter(item=>item.done).length}/${task.subtasks.length} steps`:""}</small></span></label>)}{!openTasks.length&&<div className="widget-empty"><p>No open tasks.</p><button className="text-button" onClick={()=>setQuickTask(true)}>Add one</button></div>}</div>;
  case"quickNotes":return <label className="quick-note"><span className="sr-only">Quick note</span><textarea value={String(widget.config?.text||"")} onChange={event=>updateNote(widget,event.target.value)} placeholder="Write something you want to keep in sight…"/></label>;
  case"financeOverview":return <div className="widget-finance"><div><span>Available</span><strong className="balance">{totalMoney(balance)}</strong></div><div><span>Income</span><strong className="positive">{totalMoney(income)}</strong></div><div><span>Expenses</span><strong className="negative">{totalMoney(expenses)}</strong></div><div><span>Savings</span><strong className="saving">{totalMoney(savings)}</strong></div></div>;
  case"documentsDue":return <div className="widget-list compact">{dueDocuments.slice(0,4).map(item=><button key={item.id} onClick={()=>onNavigate("Documents")}><time>{new Date(item.dueDate+"T12:00:00").toLocaleDateString(undefined,{month:"short",day:"numeric"})}</time><span><strong>{item.title}</strong><small>{item.category}</small></span></button>)}{!dueDocuments.length&&<div className="widget-empty"><p>No document deadlines.</p></div>}</div>;
  case"peopleOverview":return <div className="widget-people">{favoritePeople.map(item=><button key={item.id} onClick={()=>onNavigate("People")}><span>{item.name.split(/\s+/).map(part=>part[0]).join("").slice(0,2)}</span><strong>{item.name}</strong><small>{item.relationship||item.group}</small></button>)}{!favoritePeople.length&&<div className="widget-empty"><p>No favorite people yet.</p><button className="text-button" onClick={()=>onNavigate("People")}>Open People</button></div>}</div>;
  case"taskCompletion":return <div className="trend-widget"><strong>{completion.at(-1)?.value||0}%</strong><span>completed this month</span><Trend values={completion.map(item=>item.value)} max={100}/><div>{completion.map(item=><small key={item.label}>{item.label}</small>)}</div></div>;
  case"expenseTrend":return <div className="trend-widget"><strong>{expensePoints.at(-1)?.value.toLocaleString()||0}</strong><span>recorded this month</span><Trend values={expensePoints.map(item=>item.value)} tone="expense"/><div>{expensePoints.map(item=><small key={item.label}>{item.label}</small>)}</div></div>;
  case"wellbeing":{const point=wellbeing.at(-1);return <div className="wellbeing-widget">{(["happiness","energy","stress"] as const).map(key=><div key={key}><span>{key}</span><strong>{point?.[key]||0}/5</strong><i><b style={{width:`${(point?.[key]||0)*20}%`}}/></i></div>)}</div>}
 }};
 return <>
  <div className="dashboard-toolbar"><div><h2>My dashboard</h2><p>{editing?"Move, resize, add, or remove widgets. Changes are encrypted with your workspace.":"Arrange KirpiNova around the parts of life you want in sight."}</p></div><div><button className="secondary-button" onClick={()=>setEditing(value=>!value)}>{editing?"Finish organizing":"Organize widgets"}</button>{editing&&<><button className="secondary-button" onClick={()=>setLibrary(true)}><Plus/> Add widget</button><button className="text-button" onClick={()=>persist(resetDashboardLayout(layout))}>Reset layout</button></>}</div></div>
  {quickTask&&<aside className="quick-task-composer" id="dashboard-quick-task" aria-labelledby="quick-task-title"><header><div><h2 id="quick-task-title">Add a task now</h2><p>Keep your place on the dashboard.</p></div><button className="editor-close" type="button" onClick={()=>setQuickTask(false)}>Close</button></header><form onSubmit={saveQuickTask}><label className="field quick-task-title"><span>Task</span><input name="title" autoFocus placeholder="What needs doing?" required/></label><label className="field"><span>Due date</span><input name="dueDate" type="date"/></label><label className="field"><span>Category</span><input name="category" defaultValue="Personal"/></label><label className="field"><span>Priority</span><select name="priority" defaultValue="medium"><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></label><button className="primary-button" type="submit">Save task</button></form></aside>}
  {layout.widgets.length?<div className={editing?"custom-dashboard is-editing":"custom-dashboard"}>{layout.widgets.map((widget,index)=>{const definition=widgetDefinitions[widget.type];return <article key={widget.id} className="dashboard-widget" style={{"--widget-cols":widget.cols,"--widget-rows":widget.rows} as React.CSSProperties} draggable={editing} onDragStart={()=>setDragged(widget.id)} onDragOver={event=>editing&&event.preventDefault()} onDrop={()=>{if(editing&&dragged)persist(reorder(layout,dragged,widget.id));setDragged("")}}><header><div><h3>{definition.title}</h3><p>{definition.description}</p></div>{editing&&<div className="widget-controls"><button className="drag-handle" type="button" aria-label={`Drag ${definition.title}`} title="Drag to move"><Grip/></button><button type="button" onClick={()=>persist(moveWidget(layout,widget.id,-1))} disabled={index===0} aria-label={`Move ${definition.title} earlier`}>←</button><button type="button" onClick={()=>persist(moveWidget(layout,widget.id,1))} disabled={index===layout.widgets.length-1} aria-label={`Move ${definition.title} later`}>→</button><button type="button" onClick={()=>persist(resizeWidget(layout,widget.id,-1))} aria-label={`Make ${definition.title} narrower`}>−</button><button type="button" onClick={()=>persist(resizeWidget(layout,widget.id,1))} aria-label={`Make ${definition.title} wider`}>+</button><button type="button" onClick={()=>persist(removeWidget(layout,widget.id))} aria-label={`Remove ${definition.title}`}>Remove</button></div>}</header><div className="dashboard-widget-body">{renderWidget(widget)}</div></article>})}</div>:<div className="dashboard-empty-state"><h2>Your dashboard is empty</h2><p>Add the views and quick actions that help you run your day.</p><button className="primary-button" onClick={()=>setLibrary(true)}>Add a widget</button></div>}
  {library&&<dialog className="widget-library-dialog" ref={libraryDialog} aria-labelledby="widget-library-title" onCancel={()=>setLibrary(false)} onClose={()=>setLibrary(false)} onMouseDown={event=>{if(event.target===event.currentTarget)setLibrary(false)}}><section className="widget-library"><header><div><h2 id="widget-library-title">Add a widget</h2><p>Choose only what earns space on your dashboard.</p></div><button className="editor-close" onClick={()=>setLibrary(false)}>Close</button></header><div>{(Object.entries(widgetDefinitions) as [DashboardWidgetType,(typeof widgetDefinitions)[DashboardWidgetType]][]).map(([type,definition])=><article key={type}><div><h3>{definition.title}</h3><p>{definition.description}</p></div><button className="secondary-button" onClick={()=>{persist(addWidget(layout,type));onStatus(`${definition.title} added.`)}}>Add</button></article>)}</div></section></dialog>}
 </>;
}