"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {SubscriptionManager} from "@/components/subscription-manager";
import {emptyFinanceDraft,FinanceDraft,FinanceTransaction,financeRepository,money,TransactionType} from "@/lib/finance";
const Plus=()=> <svg aria-hidden="true" viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="M12 5v14M5 12h14"/></svg>;
const types:TransactionType[]=["income","expense","saving"];
export function FinanceWorkspace({onStatus}:{onStatus:(message:string)=>void}){
 const [items,setItems]=useState<FinanceTransaction[]>([]),[month,setMonth]=useState("2026-08"),[type,setType]=useState<"all"|TransactionType>("all"),[query,setQuery]=useState(""),[editor,setEditor]=useState(false),[editing,setEditing]=useState<string|null>(null),[draft,setDraft]=useState<FinanceDraft>(emptyFinanceDraft);
 useEffect(()=>setItems(financeRepository.load()),[]);
 const monthItems=useMemo(()=>items.filter(x=>x.date.startsWith(month)),[items,month]);
 const visible=monthItems.filter(x=>(type==="all"||x.type===type)&&(!query.trim()||[x.description,x.category,x.currency].some(v=>v.toLowerCase().includes(query.toLowerCase())))).sort((a,b)=>b.date.localeCompare(a.date)||b.createdAt.localeCompare(a.createdAt));
 const sum=(kind:TransactionType,impact?:FinanceTransaction["balanceImpact"])=>monthItems.filter(x=>x.type===kind&&(!impact||x.balanceImpact===impact)).reduce((n,x)=>n+x.amount,0);
 const income=sum("income"),expense=sum("expense"),cashSaving=sum("saving","cash"),allSaving=sum("saving"),balance=income-expense-cashSaving,rate=income>0?cashSaving/income*100:0;
 const categories=Array.from(new Set(items.map(x=>x.category))).sort();
 const commit=(next:FinanceTransaction[],message:string)=>{setItems(next);financeRepository.save(next);onStatus(message)};
 const open=(item?:FinanceTransaction)=>{setEditing(item?.id||null);setDraft(item?{type:item.type,amount:item.amount,currency:item.currency,date:item.date,description:item.description,category:item.category,balanceImpact:item.balanceImpact}:{...emptyFinanceDraft(),date:month+"-10"});setEditor(true)};
 const save=(event:FormEvent)=>{event.preventDefault();const description=draft.description.trim(),category=draft.category.trim();if(!description||!category||!Number.isFinite(draft.amount)||draft.amount<=0){onStatus("Add a description, category, and amount greater than zero.");return}const clean={...draft,description,category,balanceImpact:draft.type==="saving"?draft.balanceImpact:"cash"};const next=editing?items.map(x=>x.id===editing?{...x,...clean}:x):[...items,{...clean,id:crypto.randomUUID(),createdAt:new Date().toISOString()}];commit(next,editing?"Transaction updated.":"Transaction added.");setEditor(false)};
 const remove=()=>{if(!editing)return;commit(items.filter(x=>x.id!==editing),"Transaction deleted.");setEditor(false)};
 return <section className="finance-workspace">
  <div className="finance-summary"><div className="finance-primary"><span>Available balance</span><strong>{money(balance)}</strong><small>Income minus expenses and cash savings</small></div><div><span>Income</span><strong className="positive">{money(income)}</strong><small>This month</small></div><div><span>Expenses</span><strong className="negative">{money(expense)}</strong><small>{income?Math.round(expense/income*100):0}% of income</small></div><div><span>Savings</span><strong className="saving">{money(allSaving)}</strong><small>{rate.toFixed(1)}% cash saving rate</small></div></div>
  <div className="finance-toolbar"><label><span>Report month</span><input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label><div className="finance-filters">{(["all",...types] as const).map(value=><button key={value} className={type===value?"active":""} onClick={()=>setType(value)}>{value[0].toUpperCase()+value.slice(1)}</button>)}</div><label className="finance-search"><span className="sr-only">Search transactions</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search transactions"/></label><button className="primary-button compact" onClick={()=>open()}><Plus/> Add transaction</button></div>
  <div className={editor?"finance-layout with-editor":"finance-layout"}><div className="transaction-table"><div className="transaction-head"><span>Date</span><span>Description</span><span>Category</span><span>Amount</span></div>{visible.length===0?<div className="finance-empty"><h2>No transactions found</h2><p>Change the filters or add a transaction for this month.</p><button className="secondary-button" onClick={()=>open()}>Add transaction</button></div>:visible.map(item=><button className="transaction-row" key={item.id} onClick={()=>open(item)}><time>{new Date(item.date+"T12:00:00").toLocaleDateString(undefined,{month:"short",day:"numeric"})}</time><span><strong>{item.description}</strong><small>{item.type}{item.balanceImpact==="none"?" · prior saving":""}</small></span><span>{item.category}</span><strong className={item.type}>{item.type==="expense"?"−":"+"}{money(item.amount,item.currency)}</strong></button>)}</div>
  {editor&&<aside className="finance-editor"><div className="editor-heading"><div><span>{editing?"Editing transaction":"New transaction"}</span><h2>{editing?"Update the entry":"Record money movement"}</h2></div><button className="editor-close" onClick={()=>setEditor(false)}>Close</button></div><form onSubmit={save}><fieldset className="type-selector"><legend>Transaction type</legend>{types.map(value=><label key={value}><input type="radio" name="finance-type" checked={draft.type===value} onChange={()=>setDraft({...draft,type:value})}/><span>{value[0].toUpperCase()+value.slice(1)}</span></label>)}</fieldset><div className="editor-grid"><label className="field"><span>Amount</span><input type="number" min="0.01" step="0.01" value={draft.amount||""} onChange={e=>setDraft({...draft,amount:Number(e.target.value)})}/></label><label className="field"><span>Currency</span><select value={draft.currency} onChange={e=>setDraft({...draft,currency:e.target.value})}><option>TRY</option><option>EUR</option><option>USD</option><option>GBP</option></select></label></div><label className="field"><span>Date</span><input type="date" value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/></label><label className="field"><span>Description</span><input value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})} placeholder="What was this for?"/></label><label className="field"><span>Category</span><input list="finance-categories" value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}/><datalist id="finance-categories">{categories.map(x=><option value={x} key={x}/>)}</datalist></label>{draft.type==="saving"&&<label className="existing-saving"><input type="checkbox" checked={draft.balanceImpact==="none"} onChange={e=>setDraft({...draft,balanceImpact:e.target.checked?"none":"cash"})}/><span><strong>Existing saving</strong><small>Record prior savings without changing available balance or saving rate.</small></span></label>}<div className="editor-actions">{editing&&<button type="button" className="danger-button" onClick={remove}>Delete</button>}<span/><button type="button" className="secondary-button" onClick={()=>setEditor(false)}>Cancel</button><button className="primary-button" type="submit">{editing?"Save changes":"Add transaction"}</button></div></form></aside>}</div>
  <SubscriptionManager onStatus={onStatus} onTransactionsChanged={setItems}/>
 </section>
}
