"use client";
import {ChangeEvent,useState} from "react";
import type {CloudVaultKey} from "@/lib/cloud-vault";
import {uploadEncryptedAttachment} from "@/lib/attachment-client";
import {blankReceiptDraft,ReceiptScanResult} from "@/lib/receipt-scan";
import {FinanceTransaction,financeRepository} from "@/lib/finance";
import {preferencesRepository} from "@/lib/preferences";
const DELAY=1200,allowed=new Set(["image/jpeg","image/png","image/webp"]);
type Draft=ReceiptScanResult&{id:string;file:File;url:string;error:string;attachmentId?:string};
const toBase64=(file:File)=>new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(",")[1]||"");reader.onerror=()=>reject(new Error("Image could not be read."));reader.readAsDataURL(file)});
export function ReceiptScanner({categories,vaultKey,onSaved,onStatus}:{categories:string[];vaultKey?:CloudVaultKey;onSaved:(items:FinanceTransaction[])=>void;onStatus:(message:string)=>void}){
 const[drafts,setDrafts]=useState<Draft[]>([]),[progress,setProgress]=useState(""),[open,setOpen]=useState(false),[large,setLarge]=useState("");
 const pick=async(event:ChangeEvent<HTMLInputElement>)=>{const files=[...(event.target.files||[])].filter(file=>allowed.has(file.type)&&file.size<=8*1024*1024);event.target.value="";if(!files.length){onStatus("Choose JPEG, PNG, or WebP images up to 8 MB.");return}const key=preferencesRepository.load().geminiApiKey.trim();if(!key){onStatus("Add your Gemini API key in Settings → Receipt scanning first.");return}setOpen(true);for(let index=0;index<files.length;index++){const file=files[index];setProgress(`Scanning ${index+1} of ${files.length}… ${file.name}`);let result={...blankReceiptDraft()} as ReceiptScanResult,error="";try{const response=await fetch("/api/receipt-scan",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({apiKey:key,mimeType:file.type,imageBase64:await toBase64(file),categories})}),body=await response.json();if(!response.ok)throw new Error(body.error||"Scan failed.");result=body}catch(value){error=value instanceof Error?value.message:"Scan failed."}setDrafts(current=>[...current,{...result,id:crypto.randomUUID(),file,url:URL.createObjectURL(file),error}]);if(index<files.length-1)await new Promise(resolve=>setTimeout(resolve,DELAY))}setProgress("")};
 const update=(id:string,patch:Partial<Draft>)=>setDrafts(current=>current.map(item=>item.id===id?{...item,...patch}:item));
 const discard=(id:string)=>setDrafts(current=>{const item=current.find(value=>value.id===id);if(item)URL.revokeObjectURL(item.url);return current.filter(value=>value.id!==id)});
 const save=async(draft:Draft)=>{if(!vaultKey){onStatus("Unlock the encrypted cloud vault before saving a receipt attachment.");return}if(!draft.total||draft.total<=0||!draft.merchant?.trim()||!draft.category?.trim()){onStatus("Review amount, merchant, and category before saving.");return}try{const attachmentId=(await uploadEncryptedAttachment(draft.file,vaultKey)).id;const transaction:FinanceTransaction={id:crypto.randomUUID(),type:"expense",amount:draft.total,currency:draft.currency.toUpperCase(),date:draft.date||new Date().toISOString().slice(0,10),description:draft.merchant!.trim(),category:draft.category!.trim(),balanceImpact:"cash",createdAt:new Date().toISOString(),receiptAttachmentId:attachmentId,receiptAttachmentName:draft.file.name,receiptAttachmentType:draft.file.type};const next=[...financeRepository.load(),transaction];financeRepository.save(next);onSaved(next);discard(draft.id);onStatus("Receipt saved as an expense.")}catch(value){onStatus(value instanceof Error?value.message:"Receipt could not be saved.")}};
 return <><label className="secondary-button compact receipt-picker"><input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={pick}/>Scan receipts</label>{open&&<section className="receipt-review" aria-label="Receipt review"><header><div><span>Receipt scanning</span><h2>Review drafts</h2></div><button className="editor-close" onClick={()=>setOpen(false)}>Close</button></header>{progress&&<p className="scan-progress" role="status">{progress}</p>}<div className="receipt-drafts">{drafts.map(d=><article className={d.error||d.confidence==="low"?"receipt-draft needs-review":"receipt-draft"} key={d.id}><button className="receipt-thumb" onClick={()=>setLarge(d.url)} aria-label={`Enlarge ${d.file.name}`}><img src={d.url} alt="Receipt preview"/></button>{d.confidence==="low"&&!d.error&&<p className="receipt-warning">Low-confidence scan. Review every field before saving.</p>}{d.error&&<p className="receipt-error">Scan unavailable: {d.error} Review this blank draft manually.</p>}<div className="editor-grid"><label className="field"><span>Amount</span><input type="number" min=".01" step=".01" value={d.total||""} onChange={e=>update(d.id,{total:Number(e.target.value)})}/></label><label className="field"><span>Currency</span><input maxLength={3} value={d.currency} onChange={e=>update(d.id,{currency:e.target.value.toUpperCase()})}/></label></div><label className="field"><span>Date</span><input type="date" value={d.date||""} onChange={e=>update(d.id,{date:e.target.value||null})}/></label><label className="field"><span>Merchant / description</span><input value={d.merchant||""} onChange={e=>update(d.id,{merchant:e.target.value})}/></label><label className="field"><span>Category</span><input list="receipt-categories" value={d.category||""} onChange={e=>update(d.id,{category:e.target.value})}/></label><div className="editor-actions"><button className="secondary-button" onClick={()=>discard(d.id)}>Discard</button><button className="primary-button" onClick={()=>save(d)}>Save expense</button></div></article>)}</div><datalist id="receipt-categories">{categories.map(value=><option value={value} key={value}/>)}</datalist></section>}{large&&<button className="receipt-lightbox" onClick={()=>setLarge("")} aria-label="Close enlarged receipt"><img src={large} alt="Enlarged receipt"/></button>}</>;
}