"use client";

import { ChangeEvent, useEffect, useState } from "react";
import { AppPreferences, defaultPreferences, preferencesRepository, previewStorageKeys } from "@/lib/preferences";
import { createEncryptedArchive, restoreEncryptedArchive } from "@/lib/secure-archive";

const Eye = ({ visible }: { visible: boolean }) => <svg aria-hidden="true" viewBox="0 0 24 24" width="19" height="19" fill="none" stroke="currentColor" strokeWidth="1.8">{visible ? <><path d="m3 3 18 18"/><path d="M10.7 6.2A9.8 9.8 0 0 1 12 6c6 0 9.5 6 9.5 6a16 16 0 0 1-2.1 2.7M6.2 6.2C3.8 8 2.5 12 2.5 12s3.5 6 9.5 6c1 0 2-.2 2.8-.5"/></> : <><path d="M2.5 12s3.5-6 9.5-6 9.5 6 9.5 6-3.5 6-9.5 6-9.5-6-9.5-6Z"/><circle cx="12" cy="12" r="2.5"/></>}</svg>;
const Download = () => <svg aria-hidden="true" viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="M12 3v12m-5-5 5 5 5-5M4 20h16"/></svg>;
const Upload = () => <svg aria-hidden="true" viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="M12 21V9m-5 5 5-5 5 5M4 4h16"/></svg>;

export function SettingsWorkspace({ theme, onThemeChange, onStatus }: { theme: "light" | "dark"; onThemeChange: (theme: "light" | "dark") => void; onStatus: (message: string) => void }) {
  const [settings,setSettings] = useState<AppPreferences>(defaultPreferences), [showKey,setShowKey] = useState(false), [archivePassphrase,setArchivePassphrase] = useState(""), [restorePassphrase,setRestorePassphrase] = useState(""), [restoreFile,setRestoreFile] = useState<File|null>(null), [busy,setBusy] = useState(false);
  useEffect(() => setSettings(preferencesRepository.load()), []);
  const update = <K extends keyof AppPreferences>(key: K, value: AppPreferences[K]) => setSettings((current) => ({...current,[key]:value}));
  const save = (event:{preventDefault():void}) => { event.preventDefault(); preferencesRepository.save(settings); onStatus("Settings saved to this browser."); };
  const downloadArchive = async () => { try { setBusy(true); const source = await createEncryptedArchive(archivePassphrase); const blob = new Blob([source],{type:"application/vnd.kirpinova.archive+json"}), url=URL.createObjectURL(blob), anchor=document.createElement("a"); anchor.href=url; anchor.download=`kirpinova-${new Date().toISOString().slice(0,10)}.knv`; anchor.click(); URL.revokeObjectURL(url); setArchivePassphrase(""); onStatus("Encrypted archive downloaded."); } catch(error) { onStatus(error instanceof Error ? error.message : "Archive creation failed."); } finally { setBusy(false); } };
  const chooseRestore = (event:ChangeEvent<HTMLInputElement>) => setRestoreFile(event.target.files?.[0]||null);
  const restore = async () => { if(!restoreFile){onStatus("Choose a .knv archive first.");return} if(!window.confirm("Restore this archive into the current browser? Matching KirpiNova records will be replaced."))return; try{setBusy(true);const count=await restoreEncryptedArchive(await restoreFile.text(),restorePassphrase);onStatus(`${count} encrypted archive sections restored. Reloading…`);window.setTimeout(()=>window.location.reload(),900)}catch(error){onStatus(error instanceof Error?error.message:"Archive restore failed.")}finally{setBusy(false)} };
  const resetPreview=()=>{if(!window.confirm("Remove all KirpiNova preview data stored in this browser? Download an encrypted archive first if you want to keep it."))return;previewStorageKeys.forEach((key)=>localStorage.removeItem(key));onStatus("Preview data reset. Reloading…");window.setTimeout(()=>window.location.reload(),700)};
  return <form className="settings-workspace" onSubmit={save}><nav className="settings-index" aria-label="Settings sections"><a href="#profile-settings">Profile</a><a href="#appearance-settings">Appearance</a><a href="#reminder-settings">Reminders</a><a href="#receipt-settings">Receipt scanning</a><a href="#data-settings">Data control</a></nav><div className="settings-content">
    <section className="settings-section" id="profile-settings"><header><span>Profile</span><h2>Your workspace identity</h2><p>Used to personalize KirpiNova for you and your household.</p></header><div className="settings-fields"><label className="field"><span>Display name</span><input value={settings.displayName} onChange={(event)=>update("displayName",event.target.value)}/></label><label className="field"><span>Workspace name</span><input value={settings.workspaceName} onChange={(event)=>update("workspaceName",event.target.value)}/></label></div></section>
    <section className="settings-section" id="appearance-settings"><header><span>Appearance</span><h2>Choose a comfortable view</h2><p>Light and dark modes receive the same feature and contrast coverage.</p></header><fieldset className="theme-options"><legend>Color mode</legend>{(["light","dark"] as const).map((value)=><label key={value}><input type="radio" name="theme" checked={theme===value} onChange={()=>onThemeChange(value)}/><span><i className={`theme-swatch ${value}`}/><strong>{value[0].toUpperCase()+value.slice(1)}</strong><small>{value==="light"?"Bright, cool, and spacious":"Low-glare deep teal"}</small></span></label>)}</fieldset></section>
    <section className="settings-section" id="reminder-settings"><header><span>Reminders</span><h2>Decide how KirpiNova gets your attention</h2><p>Preferences persist now. Delivery connects during the cloud service phase.</p></header><div className="settings-fields"><label className="setting-toggle"><input type="checkbox" checked={settings.remindersEnabled} onChange={(event)=>update("remindersEnabled",event.target.checked)}/><span><strong>Enable reminders</strong><small>For tasks, documents, and subscriptions.</small></span></label><label className="field"><span>Default reminder time</span><input type="time" value={settings.reminderHour} onChange={(event)=>update("reminderHour",event.target.value)} disabled={!settings.remindersEnabled}/></label><label className="setting-toggle"><input type="checkbox" checked={settings.weekStartsMonday} onChange={(event)=>update("weekStartsMonday",event.target.checked)}/><span><strong>Start weeks on Monday</strong><small>Used by calendars and weekly summaries.</small></span></label></div></section>
    <section className="settings-section" id="receipt-settings"><header><span>Receipt scanning</span><h2>Connect your own Gemini API key</h2><p>Receipt images are sent to Google only when you explicitly scan them.</p></header><label className="field settings-secret"><span>Gemini API key</span><span className="password-field"><input type={showKey?"text":"password"} value={settings.geminiApiKey} onChange={(event)=>update("geminiApiKey",event.target.value)} autoComplete="off" placeholder="Enter your API key"/><button type="button" onClick={()=>setShowKey((value)=>!value)} aria-label={showKey?"Hide API key":"Show API key"}><Eye visible={showKey}/></button></span><small>It is included inside encrypted exports, but browser storage remains unencrypted during this preview.</small></label></section>
    <section className="settings-section" id="data-settings"><header><span>Data control</span><h2>Take your workspace with you</h2><p>Archives are encrypted in your browser before download. KirpiNova cannot recover a forgotten archive passphrase.</p></header><div className="archive-tools"><div className="archive-tool"><strong>Create encrypted archive</strong><small>Uses AES-256-GCM with a passphrase-derived key. Use at least 10 characters.</small><label className="field"><span>Archive passphrase</span><input type="password" value={archivePassphrase} onChange={(event)=>setArchivePassphrase(event.target.value)} autoComplete="new-password"/></label><button type="button" className="secondary-button" disabled={busy} onClick={downloadArchive}><Download/> Download .knv archive</button></div><div className="archive-tool"><strong>Restore encrypted archive</strong><small>Choose a KirpiNova .knv file and enter the passphrase used to create it.</small><label className="archive-file"><input type="file" accept=".knv,application/json" onChange={chooseRestore}/><Upload/><span>{restoreFile?.name||"Choose archive"}</span></label><label className="field"><span>Archive passphrase</span><input type="password" value={restorePassphrase} onChange={(event)=>setRestorePassphrase(event.target.value)} autoComplete="current-password"/></label><button type="button" className="secondary-button" disabled={busy} onClick={restore}>Restore archive</button></div><div className="archive-tool danger-zone"><strong>Reset browser preview</strong><small>Removes all KirpiNova preview records from this browser after confirmation.</small><button type="button" className="danger-button" disabled={busy} onClick={resetPreview}>Reset preview data</button></div></div></section>
    <footer className="settings-save"><span>Profile and reminder changes are kept after you save.</span><button className="primary-button" type="submit">Save settings</button></footer>
  </div></form>;
}
