"use client";

import { useEffect, useState } from "react";
import { AppPreferences, defaultPreferences, preferencesRepository, previewStorageKeys } from "@/lib/preferences";

const Eye = ({ hidden }: { hidden: boolean }) => <svg aria-hidden="true" viewBox="0 0 24 24" width="19" height="19" fill="none" stroke="currentColor" strokeWidth="1.8"><path d={hidden ? "M2.5 12s3.5-6 9.5-6 9.5 6 9.5 6-3.5 6-9.5 6-9.5-6-9.5-6Z" : "m3 3 18 18"}/>{hidden ? <circle cx="12" cy="12" r="2.5"/> : <><path d="M10.7 6.2A9.8 9.8 0 0 1 12 6c6 0 9.5 6 9.5 6a16 16 0 0 1-2.1 2.7M6.2 6.2C3.8 8 2.5 12 2.5 12s3.5 6 9.5 6c1 0 2-.2 2.8-.5"/></>}</svg>;
const Download = () => <svg aria-hidden="true" viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="M12 3v12m-5-5 5 5 5-5M4 20h16"/></svg>;

export function SettingsWorkspace({ theme, onThemeChange, onStatus }: { theme: "light" | "dark"; onThemeChange: (theme: "light" | "dark") => void; onStatus: (message: string) => void }) {
  const [settings, setSettings] = useState<AppPreferences>(defaultPreferences);
  const [showKey, setShowKey] = useState(false);
  useEffect(() => setSettings(preferencesRepository.load()), []);
  const update = <K extends keyof AppPreferences>(key: K, value: AppPreferences[K]) => setSettings((current) => ({ ...current, [key]: value }));
  const save = (event: { preventDefault(): void }) => { event.preventDefault(); preferencesRepository.save(settings); onStatus("Settings saved to this browser."); };
  const exportArchive = () => {
    const data = Object.fromEntries(previewStorageKeys.map((key) => [key, localStorage.getItem(key)]).filter(([, value]) => value !== null));
    const blob = new Blob([JSON.stringify({ format: "kirpinova-web-preview", version: 1, exportedAt: new Date().toISOString(), data }, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob), anchor = document.createElement("a"); anchor.href = url; anchor.download = `kirpinova-preview-${new Date().toISOString().slice(0,10)}.json`; anchor.click(); URL.revokeObjectURL(url); onStatus("Preview archive downloaded.");
  };
  const resetPreview = () => { if (!window.confirm("Remove all KirpiNova preview data stored in this browser? Download an archive first if you want to keep it.")) return; previewStorageKeys.forEach((key) => localStorage.removeItem(key)); onStatus("Preview data reset. Reloading…"); window.setTimeout(() => window.location.reload(), 700); };
  return <form className="settings-workspace" onSubmit={save}>
    <nav className="settings-index" aria-label="Settings sections"><a href="#profile-settings">Profile</a><a href="#appearance-settings">Appearance</a><a href="#reminder-settings">Reminders</a><a href="#receipt-settings">Receipt scanning</a><a href="#data-settings">Data control</a></nav>
    <div className="settings-content">
      <section className="settings-section" id="profile-settings"><header><span>Profile</span><h2>Your workspace identity</h2><p>Used to personalize KirpiNova for you and your household.</p></header><div className="settings-fields"><label className="field"><span>Display name</span><input value={settings.displayName} onChange={(event) => update("displayName", event.target.value)}/></label><label className="field"><span>Workspace name</span><input value={settings.workspaceName} onChange={(event) => update("workspaceName", event.target.value)}/></label></div></section>
      <section className="settings-section" id="appearance-settings"><header><span>Appearance</span><h2>Choose a comfortable view</h2><p>Light and dark modes receive the same feature and contrast coverage.</p></header><fieldset className="theme-options"><legend>Color mode</legend><label><input type="radio" name="theme" checked={theme === "light"} onChange={() => onThemeChange("light")}/><span><i className="theme-swatch light"/><strong>Light</strong><small>Bright, cool, and spacious</small></span></label><label><input type="radio" name="theme" checked={theme === "dark"} onChange={() => onThemeChange("dark")}/><span><i className="theme-swatch dark"/><strong>Dark</strong><small>Low-glare deep teal</small></span></label></fieldset></section>
      <section className="settings-section" id="reminder-settings"><header><span>Reminders</span><h2>Decide how KirpiNova gets your attention</h2><p>Preferences persist now. Browser and email delivery will connect during the cloud service phase.</p></header><div className="settings-fields"><label className="setting-toggle"><input type="checkbox" checked={settings.remindersEnabled} onChange={(event) => update("remindersEnabled", event.target.checked)}/><span><strong>Enable reminders</strong><small>For tasks, documents, and subscriptions.</small></span></label><label className="field"><span>Default reminder time</span><input type="time" value={settings.reminderHour} onChange={(event) => update("reminderHour", event.target.value)} disabled={!settings.remindersEnabled}/></label><label className="setting-toggle"><input type="checkbox" checked={settings.weekStartsMonday} onChange={(event) => update("weekStartsMonday", event.target.checked)}/><span><strong>Start weeks on Monday</strong><small>Used by calendars and weekly summaries.</small></span></label></div></section>
      <section className="settings-section" id="receipt-settings"><header><span>Receipt scanning</span><h2>Connect your own Gemini API key</h2><p>Receipt images are sent to Google only when you explicitly scan them. The key will move into your encrypted account blob in the cloud milestone.</p></header><label className="field settings-secret"><span>Gemini API key</span><span className="password-field"><input type={showKey ? "text" : "password"} value={settings.geminiApiKey} onChange={(event) => update("geminiApiKey", event.target.value)} autoComplete="off" placeholder="Enter your API key"/><button type="button" onClick={() => setShowKey((value) => !value)} aria-label={showKey ? "Hide API key" : "Show API key"}><Eye hidden={!showKey}/></button></span><small>For this local preview, the key remains in browser storage. Do not use a production key yet.</small></label></section>
      <section className="settings-section" id="data-settings"><header><span>Data control</span><h2>Keep a copy and leave cleanly</h2><p>These preview tools cover the local browser data created during the redesign. Encrypted cloud archives and restore validation come later.</p></header><div className="data-actions"><div><strong>Download preview archive</strong><small>Exports migrated module data and settings as a readable JSON development file.</small><button type="button" className="secondary-button" onClick={exportArchive}><Download/> Download archive</button></div><div className="danger-zone"><strong>Reset browser preview</strong><small>Removes KirpiNova preview records from this browser after confirmation.</small><button type="button" className="danger-button" onClick={resetPreview}>Reset preview data</button></div></div></section>
      <footer className="settings-save"><span>Changes are kept only after you save.</span><button className="primary-button" type="submit">Save settings</button></footer>
    </div>
  </form>;
}
