"use client";
import {FormEvent,useEffect,useState} from "react";
import {emptySubscriptionDraft,FinanceSubscription,FinanceSubscriptionDraft,FinanceTransaction,financeRepository,money,recordSubscription,subscriptionRepository} from "@/lib/finance";

export function SubscriptionManager({onStatus,onTransactionsChanged}:{onStatus:(message:string)=>void;onTransactionsChanged:(items:FinanceTransaction[])=>void}){
 const [items,setItems]=useState<FinanceSubscription[]>([]),[editing,setEditing]=useState<string|null>(null),[open,setOpen]=useState(false),[draft,setDraft]=useState<FinanceSubscriptionDraft>(emptySubscriptionDraft);
 useEffect(()=>setItems(subscriptionRepository.load()),[]);
 const persist=(next:FinanceSubscription[])=>{setItems(next);subscriptionRepository.save(next)};
 const edit=(item?:FinanceSubscription)=>{setEditing(item?.id||null);setDraft(item?{name:item.name,amount:item.amount,currency:item.currency,category:item.category,nextDueDate:item.nextDueDate,frequency:item.frequency,active:item.active}:emptySubscriptionDraft());setOpen(true)};
 const save=(event:FormEvent)=>{event.preventDefault();const name=draft.name.trim(),category=draft.category.trim();if(!name||!category||draft.amount<=0){onStatus("Add a name, category, and amount greater than zero.");return}const next=editing?items.map(item=>item.id===editing?{...item,...draft,name,category}:item):[...items,{...draft,name,category,id:crypto.randomUUID(),createdAt:new Date().toISOString()}];persist(next);setOpen(false);onStatus(editing?"Subscription updated.":"Subscription added.")};
 const record=(item:FinanceSubscription)=>{try{const result=recordSubscription(item,new Date().toISOString().slice(0,10));const transactions=[...financeRepository.load(),result.transaction];financeRepository.save(transactions);persist(items.map(value=>value.id===item.id?result.subscription:value));onTransactionsChanged(transactions);onStatus(`${item.name} recorded in today’s transactions.`)}catch(error){onStatus(error instanceof Error?error.message:"Subscription could not be recorded.")}};
 const remove=()=>{if(!editing)return;persist(items.filter(item=>item.id!==editing));setOpen(false);onStatus("Subscription deleted.")};
 return <section className="subscription-panel"><div className="section-heading"><div><span className="horizon-marker">Recurring</span><h2>Subscriptions</h2><p>Record a payment when it happens; KirpiNova adds it to today’s transactions.</p></div><button className="primary-button compact" onClick={()=>edit()}>Add subscription</button></div>
  <div className="subscription-list">{items.length===0?<div className="finance-empty compact-empty"><h2>No subscriptions yet</h2><p>Add recurring payments to keep their due dates together.</p></div>:items.sort((a,b)=>a.nextDueDate.localeCompare(b.nextDueDate)).map(item=><article className="subscription-card" key={item.id}><div><span>{item.active?"Active":"Paused"}</span><h3>{item.name}</h3><p>{item.frequency} · Next {new Date(item.nextDueDate+"T12:00:00").toLocaleDateString()}</p></div><strong>{money(item.amount,item.currency)}</strong><div className="subscription-actions"><button className="secondary-button compact" onClick={()=>edit(item)}>Edit</button><button className="primary-button compact" disabled={!item.active} onClick={()=>record(item)}>Record</button></div></article>)}</div>
  {open&&<aside className="finance-editor subscription-editor"><div className="editor-heading"><div><span>{editing?"Editing subscription":"New subscription"}</span><h2>{editing?"Update recurring payment":"Track a recurring payment"}</h2></div><button className="editor-close" onClick={()=>setOpen(false)}>Close</button></div><form onSubmit={save}><label className="field"><span>Name</span><input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} placeholder="Streaming service"/></label><div className="editor-grid"><label className="field"><span>Amount</span><input type="number" min="0.01" step="0.01" value={draft.amount||""} onChange={e=>setDraft({...draft,amount:Number(e.target.value)})}/></label><label className="field"><span>Currency</span><select value={draft.currency} onChange={e=>setDraft({...draft,currency:e.target.value})}><option>TRY</option><option>EUR</option><option>USD</option><option>GBP</option></select></label></div><label className="field"><span>Category</span><input value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}/></label><div className="editor-grid"><label className="field"><span>Next due</span><input type="date" value={draft.nextDueDate} onChange={e=>setDraft({...draft,nextDueDate:e.target.value})}/></label><label className="field"><span>Repeats</span><select value={draft.frequency} onChange={e=>setDraft({...draft,frequency:e.target.value as FinanceSubscription["frequency"]})}><option value="monthly">Monthly</option><option value="yearly">Yearly</option></select></label></div><label className="setting-toggle"><input type="checkbox" checked={draft.active} onChange={e=>setDraft({...draft,active:e.target.checked})}/><span><strong>Active subscription</strong><small>Paused subscriptions cannot be recorded.</small></span></label><div className="editor-actions">{editing&&<button type="button" className="danger-button" onClick={remove}>Delete</button>}<span/><button type="button" className="secondary-button" onClick={()=>setOpen(false)}>Cancel</button><button className="primary-button">Save subscription</button></div></form></aside>}
 </section>
}