import { previewStorageKeys } from "@/lib/preferences";

export type CloudVaultEnvelope={format:"kirpinova-cloud-vault";version:1;cipher:"AES-GCM";kdf:"PBKDF2-SHA-256";iterations:number;salt:string;iv:string;ciphertext:string};
export type CloudVaultKey={key:CryptoKey;salt:Uint8Array;iterations:number};
const ITERATIONS=600_000,AAD=new TextEncoder().encode("kirpinova-cloud-vault-v1"),encoder=new TextEncoder(),decoder=new TextDecoder();
const toBase64=(bytes:Uint8Array)=>{let result="";for(let index=0;index<bytes.length;index+=0x8000)result+=String.fromCharCode(...bytes.subarray(index,index+0x8000));return btoa(result)};
const fromBase64=(value:string)=>Uint8Array.from(atob(value),character=>character.charCodeAt(0));
async function derive(passphrase:string,salt:Uint8Array,iterations=ITERATIONS){const material=await crypto.subtle.importKey("raw",encoder.encode(passphrase),"PBKDF2",false,["deriveKey"]);return crypto.subtle.deriveKey({name:"PBKDF2",hash:"SHA-256",salt:salt as BufferSource,iterations},material,{name:"AES-GCM",length:256},false,["encrypt","decrypt"])}
export function collectWorkspace(){return Object.fromEntries(previewStorageKeys.map(key=>[key,localStorage.getItem(key)]).filter((entry):entry is[string,string]=>entry[1]!==null))}
export function workspaceFingerprint(){return JSON.stringify(collectWorkspace())}
export async function createCloudVault(passphrase:string){if(passphrase.length<12)throw new Error("Use a vault passphrase with at least 12 characters.");const salt=crypto.getRandomValues(new Uint8Array(16)),key=await derive(passphrase,salt);return{vaultKey:{key,salt,iterations:ITERATIONS},envelope:await encryptCloudVault({key,salt,iterations:ITERATIONS})}}
export async function encryptCloudVault(vaultKey:CloudVaultKey){const iv=crypto.getRandomValues(new Uint8Array(12)),payload=encoder.encode(JSON.stringify({format:"kirpinova-workspace",version:1,data:collectWorkspace()})),encrypted=await crypto.subtle.encrypt({name:"AES-GCM",iv:iv as BufferSource,additionalData:AAD as BufferSource},vaultKey.key,payload);const envelope:CloudVaultEnvelope={format:"kirpinova-cloud-vault",version:1,cipher:"AES-GCM",kdf:"PBKDF2-SHA-256",iterations:vaultKey.iterations,salt:toBase64(vaultKey.salt),iv:toBase64(iv),ciphertext:toBase64(new Uint8Array(encrypted))};return JSON.stringify(envelope)}
export async function unlockCloudVault(source:string,passphrase:string){let envelope:CloudVaultEnvelope;try{envelope=JSON.parse(source)}catch{throw new Error("Cloud vault is damaged.")}if(envelope.format!=="kirpinova-cloud-vault"||envelope.version!==1||envelope.cipher!=="AES-GCM"||envelope.kdf!=="PBKDF2-SHA-256"||envelope.iterations!==ITERATIONS)throw new Error("Cloud vault format is not supported.");try{const salt=fromBase64(envelope.salt),iv=fromBase64(envelope.iv),key=await derive(passphrase,salt,envelope.iterations),clear=await crypto.subtle.decrypt({name:"AES-GCM",iv:iv as BufferSource,additionalData:AAD as BufferSource},key,fromBase64(envelope.ciphertext) as BufferSource),payload=JSON.parse(decoder.decode(clear));if(payload?.format!=="kirpinova-workspace"||payload?.version!==1||typeof payload.data!=="object")throw new Error("invalid");const allowed=new Set(previewStorageKeys);for(const[storageKey,value]of Object.entries(payload.data))if(allowed.has(storageKey)&&typeof value==="string")localStorage.setItem(storageKey,value);return{key,salt,iterations:envelope.iterations} satisfies CloudVaultKey}catch{throw new Error("Vault passphrase is incorrect, or the cloud vault is damaged.")}}
