import { isTrustedMutation } from "@/lib/server/origin";
import { currentUser } from "@/lib/server/auth/session";
import { jsonError,readJson } from "@/lib/server/auth/request";
import { getDatabasePool } from "@/lib/server/database";

export const runtime="nodejs";export const dynamic="force-dynamic";
const MAX_ENVELOPE_BYTES=16*1024*1024;
function validEnvelope(value:unknown){if(typeof value!=="string")return false;const bytes=new TextEncoder().encode(value).byteLength;if(bytes<80||bytes>MAX_ENVELOPE_BYTES)return false;try{const parsed=JSON.parse(value);return parsed?.format==="kirpinova-cloud-vault"&&parsed?.version===1&&parsed?.cipher==="AES-GCM"&&parsed?.kdf==="PBKDF2-SHA-256"&&typeof parsed.salt==="string"&&typeof parsed.iv==="string"&&typeof parsed.ciphertext==="string"}catch{return false}}
export async function GET(){const user=await currentUser();if(!user)return jsonError("Authentication required.",401);const result=await getDatabasePool().query<{revision:string;format_version:number;encrypted_envelope:string;updated_at:Date}>("select revision::text,format_version,encrypted_envelope,updated_at from encrypted_vault where user_id=$1",[user.id]);if(!result.rows[0])return Response.json({exists:false},{status:404,headers:{"Cache-Control":"no-store"}});return Response.json({exists:true,revision:Number(result.rows[0].revision),formatVersion:result.rows[0].format_version,envelope:result.rows[0].encrypted_envelope,updatedAt:result.rows[0].updated_at},{headers:{"Cache-Control":"no-store"}})}
export async function PUT(request:Request) {
  if(!isTrustedMutation(request))return jsonError("Cross-site requests are not allowed.",403);const user=await currentUser();if(!user)return jsonError("Authentication required.",401);try{const body=await readJson(request),envelope=body.envelope,expectedRevision=Number(body.expectedRevision);if(!Number.isSafeInteger(expectedRevision)||expectedRevision<0)return jsonError("Vault revision is invalid.");if(!validEnvelope(envelope))return jsonError("Encrypted vault envelope is invalid.");const bytes=new TextEncoder().encode(envelope as string).byteLength,database=getDatabasePool();if(expectedRevision===0){const inserted=await database.query<{revision:string}>("insert into encrypted_vault(user_id,revision,format_version,encrypted_envelope,envelope_bytes) values($1,1,1,$2,$3) on conflict(user_id) do nothing returning revision::text",[user.id,envelope,bytes]);if(!inserted.rows[0]){const current=await database.query<{revision:string}>("select revision::text from encrypted_vault where user_id=$1",[user.id]);return Response.json({ok:false,error:"Vault changed on another device.",currentRevision:Number(current.rows[0]?.revision||0)},{status:409})}return Response.json({ok:true,revision:1})}const updated=await database.query<{revision:string}>("update encrypted_vault set revision=revision+1,format_version=1,encrypted_envelope=$1,envelope_bytes=$2,updated_at=now() where user_id=$3 and revision=$4 returning revision::text",[envelope,bytes,user.id,expectedRevision]);if(!updated.rows[0]){const current=await database.query<{revision:string}>("select revision::text from encrypted_vault where user_id=$1",[user.id]);return Response.json({ok:false,error:"Vault changed on another device.",currentRevision:Number(current.rows[0]?.revision||0)},{status:409})}return Response.json({ok:true,revision:Number(updated.rows[0].revision)})}catch(error){return jsonError(error instanceof Error?error.message:"Vault save failed.",500)}}
